In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

### 1. Cài đặt bằng tay

In [2]:
data = np.array([[10,39,19,23,28,20],[43,13,32,21,20,10],[5,10,15,20,25,30]]).astype('float')

data[0] = data[0]-np.mean(data[0])
data[1] = data[1]-np.mean(data[1])
data[2] = data[2] -np.mean(data[2])

sz = len(data[0])-1

xy = (data[0]*data[1]).sum()/sz
xz = (data[0]*data[2]).sum()/sz
yz = (data[1]*data[2]).sum()/sz

xx,yy,zz = (data[0]**2/sz).sum(), (data[1]**2/sz).sum(), (data[2]**2).sum()/sz

cov  = np.array([[xx,xy,xz],[xy,yy,yz],[xz,yz,zz]])
cov 

array([[ 94.96666667, -86.43333333,  10.5       ],
       [-86.43333333, 152.56666667, -77.5       ],
       [ 10.5       , -77.5       ,  87.5       ]])

In [3]:
w,v = np.linalg.eig(cov)
print(v)

v[:,[0,1]].T@data 

[[-0.47371567  0.67887377  0.56100255]
 [ 0.77853003  0.02503069  0.62710801]
 [-0.4116849  -0.73382823  0.54038104]]


array([[ 26.82416316, -12.3279167 ,   9.8800428 ,  -2.6370747 ,
         -7.84260759, -13.89660697],
       [  0.73079026,  15.99806771,  -0.7729657 ,  -2.00194936,
         -2.30175235, -11.65219056]])

### 2. Sử dụng thư viện sklean

In [4]:
data = data.astype(float)
pca = PCA(n_components=2) 
data_pca = pca.fit_transform(data.T).T
# In kết quả
print("Components:")
print(pca.components_)
print("Transformed data:")

data_pca

Components:
[[-0.47371567  0.77853003 -0.4116849 ]
 [ 0.67887377  0.02503069 -0.73382823]]
Transformed data:


array([[ 26.82416316, -12.3279167 ,   9.8800428 ,  -2.6370747 ,
         -7.84260759, -13.89660697],
       [  0.73079026,  15.99806771,  -0.7729657 ,  -2.00194936,
         -2.30175235, -11.65219056]])